name: nnUNet
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - tqdm
  - dicom2nifti
  - numpy
  - scipy
  - pandas
  - requests
  - seaborn
  - matplotlib
  - scikit-learn
  - scikit-image>=0.19.3
  - SimpleITK>=2.2.1
  - graphviz
  - tifffile
  - nibabel
  - imagecodecs
  - yacs
  - einops
  - pip
  - pip:
      - batchgenerators==0.25
      - batchgeneratorsv2==0.1.1
      - acvl-utils==0.2
      - dynamic-network-architectures==0.3.1
      - nnunetv2

